name: Test and Build image

on:
  push:
    tags:
    - '*'
    branches:
    - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.12-alpine

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: pr_user
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Install APK packages
      run: |
        apk update
        apk add --virtual build-dependencies build-base
        apk add bash nodejs npm inotify-tools openssl

    - uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get

    - name: Run Tests
      run: mix test
      env:
        # use postgres for the host here because we have specified a container for the job.
        # If we were running the job on the VM this would be localhost
        POSTGRES_HOST: postgres
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}

  release:
    runs-on: ubuntu-latest
    needs: test

    if: startsWith(github.ref, 'refs/tags/')

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

    - uses: actions/checkout@v1

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        APP_REVISION: ${{ github.ref_name }}
      with:
        name: errkk/playrequest/pr
        username: _
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        dockerfile: Dockerfile
        buildargs: APP_REVISION
        tags: "latest,${{ github.ref_name }}"
